### ISSUE TITLE
Animal is missing from response

### ISSUE THREAD

**Issue by nrathi** [petfinder-com/petfinder-js-sdk#16]
Hi, 

It seems like every animal from organization `MA480` is missing (`client.animal.search({"organization": "MA480"})` returned `[]`).

Thanks!

**Comment by nrathi** [comment]
Upon further investigation, it seems like every animal from organization `MA480` is missing (`client.animal.search({"organization": "MA480"})` returned `[]`).

**Comment by ivorisoutdoors** [comment]
Petfinder allows organizations to de-list animals from the public API. It sounds like this is what's happening

**Comment by nrathi** [comment]
Got it, thanks!
