### ISSUE TITLE
Pet not found

### ISSUE THREAD

**Issue by reallukedev** [petfinder-com/petfinder-js-sdk#21]
Sometimes, when searching for a pet, event though the pet is on the website, Petfinder API says that the pet is not found

Example:
https://www.petfinder.com/dog/ms-wiggles-52649180/la/lafayette/lafayette-animal-shelter-care-center-lascc-la40/
`
pf.animal.show(52649180).then(function(response) {
    console.log(response);
}).catch(function(error) {
    console.log(error);
});
`

![image](https://user-images.githubusercontent.com/58954397/129484768-cec0e8ff-4654-40f8-99ff-a6fb2b6c8fef.png)

**Comment by ivorisoutdoors** [comment]
Petfinder allows organizations to de-list their animals from the api.

#16
