### ISSUE TITLE
Petfinder's image host does not support `https` (invalid cert)

### ISSUE THREAD

**Issue by ZacSweers** [petfinder-com/petfinder-js-sdk#22]
Hello! I'm helping a local animal rescue that uses Petfinder debug why their website doesn't show embedded petfinder images.

It appears that petfinder's certificate is invalid and does not support https when attempting to load photos. Is this something that they're doing wrong in their website or is something wrong on petfinder's side?

Example image: `https://photos.petfinder.com/photos/pets/55025850/1/`

Note that it loads fine with `http`, but this isn't viable anymore as [browsers refuse to load mixed content](https://www.searchenginejournal.com/chrome-81-will-not-load-mixed-content/358298/) and will automatically upgrade the `http` urls to `https`. 

<img width="737" alt="image" src="https://user-images.githubusercontent.com/1361086/160307900-ddb12fdb-1ef3-4798-88f2-8eee297b0dfc.png">

**Comment by petfinder-darla** [comment]
Hi @ZacSweers thanks for reaching out! We are looking into this now. Could you help me understand where you are getting URLs that use [photos.petfinder.com](http://photos.petfinder.com/)? If it's from the public API, can you give us a pet id that is pointing you at that domain?

**Comment by ZacSweers** [comment]
They are coming from petfinder's API using this SDK. I included an example URL (which has the pet ID in it) in the description

```
https://photos.petfinder.com/photos/pets/55025850/1/
```

The ID is `55025850`

**Comment by petfinder-darla** [comment]
@ZacSweers This issue should be solved! Could you please confirm you are no longer seeing the issue?

**Comment by ZacSweers** [comment]
Looks like it! Thanks for the quick resolution
