### ISSUE TITLE
Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by catbai** [petfinder-com/petfinder-js-sdk#4]
This package works great, but I'm left with this error in my console. 

`Refused to set unsafe header "User-Agent"`

Please how can I get rid of the error? Thanks

**Comment by ivorisoutdoors** [comment]
Thanks for bringing this to our attention! We have identified the issue and will be pushing out a fix in the next day or so

**Comment by ivorisoutdoors** [comment]
We've fixed this issue. Published as 1.0.3
